import { createFileRoute, Link, notFound } from "@tanstack/react-router";
import { useSuspenseQuery } from "@tanstack/react-query";
import { ArrowLeft, Download, FileText, MapPin, Mail, Phone, BriefcaseBusiness, GraduationCap } from "lucide-react";
import { useState } from "react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { candidateQueryKeys, candidateService } from "@/lib/api/candidate-service";
import { formatUploaded, SkillList } from "@/components/candidates/candidate-parts";

export const Route = createFileRoute("/_workspace/candidates/$id")({
  loader: async ({ context, params }) => { const candidate = await context.queryClient.ensureQueryData({ queryKey: candidateQueryKeys.detail(params.id), queryFn: () => candidateService.getCandidate(params.id) }); if (!candidate) throw notFound(); return candidate; },
  head: ({ loaderData }) => ({ meta: [{ title: `${loaderData?.name ?? "Candidate"} | Archivum` }, { name: "description", content: `Candidate profile and resume details for ${loaderData?.name ?? "a recruiter candidate"}.` }, { property: "og:title", content: `${loaderData?.name ?? "Candidate"} | Archivum` }, { property: "og:description", content: `Profile and experience details for ${loaderData?.name ?? "a candidate"}.` }, { property: "og:type", content: "profile" }, { name: "twitter:card", content: "summary" }] }),
  component: CandidateProfilePage,
});

function CandidateProfilePage() {
  const { id } = Route.useParams();
  const { data: candidate } = useSuspenseQuery({ queryKey: candidateQueryKeys.detail(id), queryFn: () => candidateService.getCandidate(id) });
  const [showResume, setShowResume] = useState(false);
  if (!candidate) return <div className="py-20 text-center"><h1 className="text-xl font-semibold">Candidate not found</h1><Button asChild variant="outline" className="mt-4"><Link to="/candidates">Back to candidates</Link></Button></div>;
  return <div className="space-y-6">
    <Button asChild variant="ghost" size="sm"><Link to="/candidates"><ArrowLeft size={15} /> Back to candidates</Link></Button>
    <section className="flex flex-col justify-between gap-5 border-y border-border py-5 sm:flex-row sm:items-center"><div className="flex items-center gap-4"><span className="grid size-14 place-items-center rounded-md bg-accent-soft text-lg font-semibold">{candidate.name.split(" ").map((part) => part[0]).slice(0, 2).join("")}</span><div><p className="font-mono text-[9px] uppercase text-accent">Candidate profile</p><h1 className="mt-1 text-2xl font-semibold">{candidate.name}</h1><p className="mt-1 text-sm text-muted-foreground">{candidate.currentRole} · {candidate.experienceYears} years experience</p><p className="mt-1 inline-flex items-center gap-1 text-xs text-muted-foreground"><MapPin size={12} />{candidate.location}</p></div></div><div className="flex gap-2"><Button onClick={() => setShowResume(true)}><FileText size={15} /> View resume</Button><Button variant="outline" onClick={() => setShowResume(true)}><Download size={15} /> Download</Button></div></section>
    <div className="grid items-start gap-6 lg:grid-cols-[minmax(0,1fr)_280px]"><div className="space-y-7"><section><h2 className="text-base font-semibold">Professional summary</h2><p className="mt-3 max-w-3xl text-sm leading-6 text-muted-foreground">{candidate.summary}</p></section><section><h2 className="mb-3 text-base font-semibold">Experience</h2><div className="space-y-5 border-l border-border pl-5">{candidate.experience.map((item) => <div key={`${item.company}-${item.title}`} className="relative"><span className="absolute -left-[25px] top-1 size-2 rounded-full bg-accent ring-4 ring-background" /><h3 className="text-sm font-semibold">{item.title}</h3><p className="mt-1 text-sm text-muted-foreground">{item.company} · {item.period}</p><ul className="mt-2 list-disc space-y-1 pl-4 text-xs leading-5 text-muted-foreground">{item.highlights.map((highlight) => <li key={highlight}>{highlight}</li>)}</ul></div>)}</div></section><section><h2 className="mb-3 text-base font-semibold">Projects</h2><div className="divide-y divide-border border-y border-border">{candidate.projects.map((project) => <div key={project.name} className="py-4"><h3 className="text-sm font-medium">{project.name}</h3><p className="mt-1 text-xs leading-5 text-muted-foreground">{project.description}</p><div className="mt-2"><SkillList skills={project.stack} /></div></div>)}</div></section><section><h2 className="mb-3 text-base font-semibold">Education</h2>{candidate.education.map((education) => <div key={education.school} className="flex gap-3 border-y border-border py-3"><GraduationCap size={17} className="mt-0.5 text-muted-foreground" /><div><h3 className="text-sm font-medium">{education.degree}</h3><p className="mt-1 text-xs text-muted-foreground">{education.school} · {education.period}</p></div></div>)}</section></div>
      <aside className="space-y-5 border-t border-border pt-5 lg:border-l lg:border-t-0 lg:pl-5 lg:pt-0"><section><h2 className="text-sm font-semibold">Contact</h2><div className="mt-3 space-y-3 text-xs text-muted-foreground"><a className="flex items-center gap-2 break-all hover:text-foreground" href={`mailto:${candidate.email}`}><Mail size={14} />{candidate.email}</a><a className="flex items-center gap-2 hover:text-foreground" href={`tel:${candidate.phone}`}><Phone size={14} />{candidate.phone}</a><p className="flex items-center gap-2"><MapPin size={14} />{candidate.location}</p></div></section><section className="border-t border-border pt-4"><h2 className="mb-3 text-sm font-semibold">Skills</h2><div className="flex flex-wrap gap-1.5">{candidate.skills.map((skill) => <Badge key={skill} variant="secondary" className="rounded font-normal">{skill}</Badge>)}</div></section><section className="border-t border-border pt-4"><h2 className="mb-2 text-sm font-semibold">Certifications</h2>{candidate.certifications.map((cert) => <p key={cert} className="flex items-center gap-2 py-1 text-xs text-muted-foreground"><BriefcaseBusiness size={13} />{cert}</p>)}</section><section className="border-t border-border pt-4"><h2 className="text-sm font-semibold">Archive details</h2><p className="mt-2 text-xs text-muted-foreground">Added {formatUploaded(candidate.uploadedAt)}</p><p className="mt-1 text-xs text-muted-foreground">Availability: {candidate.availability}</p></section></aside></div>
    {showResume && <div role="dialog" aria-modal="true" aria-labelledby="resume-title" className="fixed inset-0 z-50 grid place-items-center bg-foreground/40 p-4" onClick={() => setShowResume(false)}><div className="w-full max-w-lg rounded-lg border border-border bg-background p-6 shadow-xl" onClick={(event) => event.stopPropagation()}><h2 id="resume-title" className="text-base font-semibold">{candidate.name} · Resume</h2><p className="mt-1 text-xs text-muted-foreground">No original resume file is attached to this sample profile.</p><div className="my-5 border-y border-border py-8 text-center text-sm">A connected service must provide the PDF to view or download it.</div><div className="flex justify-end"><Button variant="outline" onClick={() => setShowResume(false)}>Close</Button></div></div></div>}
  </div>;
}
